/* File generated by: simse.codegenerator.stategenerator.LoggerGenerator */
package simse.state.logger;

import java.util.ArrayList;

import simse.state.State;

public class Logger {
	private State state; // current state
	private ArrayList<State> log; // an array list of states for the current
									// simulation

	public Logger(State state) {
		this.state = state;
		log = new ArrayList<State>();
	}

	public Logger(State state, ArrayList<State> log) {
		this.state = state;
		this.log = log;
	}

	// returns the state log
	public ArrayList<State> getLog() {
		return log;
	}

	// updates the log with the current state
	public void update() {
		log.add((State) state.clone());
	}
}