/* File generated by: simse.codegenerator.stategenerator.ADTGenerator */
package simse.adts.objects;

public class DesignDocument extends Artifact implements Cloneable {
	private String name;
	private double size;
	private double numknownerrors;
	private double numunknownerrors;
	private double percenterroneous;
	private double percentcomplete;
	private double numunknowntemp;
	private int completenessdiffreqdoc;

	public DesignDocument(String n0, double s1, double n2, double n3,
			double p4, double p5, double n6, int c7) {
		super(n0, s1, n2, n3, p4, p5, n6);
		setCompletenessDiffReqDoc(c7);
	}

	public Object clone() {
		DesignDocument cl = (DesignDocument) (super.clone());
		cl.name = name;
		cl.size = size;
		cl.numknownerrors = numknownerrors;
		cl.numunknownerrors = numunknownerrors;
		cl.percenterroneous = percenterroneous;
		cl.percentcomplete = percentcomplete;
		cl.numunknowntemp = numunknowntemp;
		cl.completenessdiffreqdoc = completenessdiffreqdoc;
		return cl;
	}

	public int getCompletenessDiffReqDoc() {
		return completenessdiffreqdoc;
	}

	public void setCompletenessDiffReqDoc(int a) {
		if (a < 0) {
			completenessdiffreqdoc = 0;
		} else if (a > 1) {
			completenessdiffreqdoc = 1;
		} else {
			completenessdiffreqdoc = a;
		}
	}

}