/* File generated by: simse.codegenerator.stategenerator.ADTGenerator */
package simse.adts.objects;

public class RequirementsCaptureTool extends Tool implements Cloneable {
	private String name;
	private double cost;
	private double productivityincreasefactor;
	private double errorratedecreasefactor;
	private boolean purchased;

	public RequirementsCaptureTool(String n0, double c1, double p2, double e3,
			boolean p4) {
		super(n0, c1, p2, e3, p4);
	}

	public Object clone() {
		RequirementsCaptureTool cl = (RequirementsCaptureTool) (super.clone());
		cl.name = name;
		cl.cost = cost;
		cl.productivityincreasefactor = productivityincreasefactor;
		cl.errorratedecreasefactor = errorratedecreasefactor;
		cl.purchased = purchased;
		return cl;
	}

	@Override
	public String getDescription() {
		return "Requirements Capture Tool";
	}

}