/* File generated by: simse.codegenerator.stategenerator.ADTGenerator */
package simse.adts.objects;

public class SystemTestPlan extends Artifact implements Cloneable {
	private String name;
	private double size;
	private double numknownerrors;
	private double numunknownerrors;
	private double percenterroneous;
	private double percentcomplete;
	private double numunknowntemp;
	private int completnessdiffreqdoc;

	public SystemTestPlan(String n0, double s1, double n2, double n3,
			double p4, double p5, double n6, int c7) {
		super(n0, s1, n2, n3, p4, p5, n6);
		setCompletnessDiffReqDoc(c7);
	}

	public Object clone() {
		SystemTestPlan cl = (SystemTestPlan) (super.clone());
		cl.name = name;
		cl.size = size;
		cl.numknownerrors = numknownerrors;
		cl.numunknownerrors = numunknownerrors;
		cl.percenterroneous = percenterroneous;
		cl.percentcomplete = percentcomplete;
		cl.numunknowntemp = numunknowntemp;
		cl.completnessdiffreqdoc = completnessdiffreqdoc;
		return cl;
	}

	public int getCompletnessDiffReqDoc() {
		return completnessdiffreqdoc;
	}

	public void setCompletnessDiffReqDoc(int a) {
		if (a < 0) {
			completnessdiffreqdoc = 0;
		} else if (a > 1) {
			completnessdiffreqdoc = 1;
		} else {
			completnessdiffreqdoc = a;
		}
	}

}