/* File generated by: simse.codegenerator.CodeGenerator */
package simse;

import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ArrayList;

import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.stage.Stage;
import javafx.util.Duration;
import simse.engine.Engine;
import simse.explanatorytool.Branch;
import simse.explanatorytool.MultipleTimelinesBrowser;
import simse.gui.SimSEGUI;
import simse.logic.Logic;
import simse.state.State;
import simse.util.RuleCategories;

public class SimSE extends Application{
	private static ArrayList<Branch> branches = new ArrayList<Branch>();
	private static ArrayList<SimSEGUI> guis = new ArrayList<SimSEGUI>();
	private static MultipleTimelinesBrowser timelinesBrowser = new MultipleTimelinesBrowser();
	private static Engine engine;
	private static SimSEGUI gui;

	public static void startNewBranch(State state, Branch branch) {
		Logic logic = new Logic(state);
		engine = new Engine(logic, state);
		gui = new SimSEGUI(engine, state, logic, branch, timelinesBrowser);
		RuleCategories.initializeRuleCategories();
		engine.giveGUI(gui);
		state.getClock().setGUI(gui);
		gui.setX(0);
		gui.setY(0);
		gui.setWidth(1024);
		gui.setHeight(744);
		logic.getTriggerChecker().update(false, gui);
		branches.add(branch);
		guis.add(gui);
		timelinesBrowser.update();
	}

	public static ArrayList<Branch> getBranches() {
		return branches;
	}

	// returns total number of open branches
	public static int getNumOpenBranches() {
		int numOpen = 0;
		for (Branch b : branches) {
			if (!b.isClosed()) {
				numOpen++;
			}
		}
		return numOpen;
	}

	public static ArrayList<SimSEGUI> getGUIs() {
		return guis;
	}

	public static void main(String args[]) {
		launch(args);
	}

	@Override
	public void start(Stage arg0) throws Exception {
		startNewBranch(new State(), new Branch(null, 0, 0, null, ""));
		ArrayList<SimSEGUI> guis = this.getGUIs();
		arg0 = guis.get(0);
		arg0.show();
		RuleCategories.initializeRuleCategories();
		engine.giveGUI(gui);
	}
}