/* File generated by: simse.codegenerator.guigenerator.PopupListenerGenerator */
package simse.gui;

import javafx.event.EventHandler;
import javafx.scene.Node;
import javafx.scene.control.ContextMenu;
import javafx.scene.input.MouseEvent;

public class PopupListener implements EventHandler<MouseEvent> {
	ContextMenu popup;
	boolean enabled;
	SimSEGUI gui;

	public PopupListener(ContextMenu popupMenu, SimSEGUI g) {
		popup = popupMenu;
		enabled = true;
		gui = g;
	}

	public boolean isEnabled() {
		return enabled;
	}

	public void setEnabled(boolean e) {
		enabled = e;
	}

	public ContextMenu getPopupMenu() {
		return popup;
	}

	@Override
	public void handle(MouseEvent e) {
		// disable the popup if the engine is running
		if (e.isPopupTrigger() && isEnabled() && !gui.getEngine().isRunning()) {
			popup.show((Node) e.getSource(), e.getX(), e.getY());
		}
	}
}